# Generated by Django 2.1.3 on 2018-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('cart', '0002_auto_20181123_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernumber',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.DeleteModel(
            name='OrderNumber',
        ),
    ]
